### ISSUE TITLE
whereami command throws NameError

### ISSUE THREAD

**Issue by EthanZeigler** [garmoshka-mo/pry-moves#14]
**Description:**
Using the whereami command, an error is raised. This includes when used by pry itself after hitting a breakpoint.

```
NameError: undefined local variable or method `text' for #<Pry::Command::Whereami:0x00000000064d6da8> from pry-moves/pry_ext.rb:60:in `build_output'
```

**Gemfile:**
```
  gem 'pry', group: :development
  gem 'pry-byebug', group: :development
  gem 'pry-moves', group: :development
  gem 'pry-rescue', group: :development
```

**Versions:**
```
  * pry (0.13.1)
  * pry-byebug (3.9.0)
  * pry-moves (0.1.12)
  * pry-rescue (1.5.2)
```

**Comment by garmoshka-mo** [comment]
Latest `pry-moves` gem version has downgraded support of pry gem (below 0.13) because of code incompatibility.
`gem.add_runtime_dependency 'pry', '>= 0.10.4', '< 0.13'`

If you can debug `pry-moves` with pry 0.13+ and fix issues, please let me know

**Comment by EthanZeigler** [comment]
Same issue. 
```
before_session hook failed: NameError: undefined local variable or method `text' for #<Pry::Command::Whereami:0x00000000046f09d8>
Did you mean?  test
/nix/store/5nygxxi6vm5gf0m4dq67y6gf8pqsnv2y-ruby2.7.4-pry-moves-0.1.12/lib/ruby/gems/2.7.0/gems/pry-moves-0.1.12/lib/pry-moves/pry_ext.rb:60:in `build_output'
(see pry_instance.hooks.errors to debug)
```
